# The maximum depth of the tree.
max_depth: 14

# The depth of the tree where the goals are located.
goals_depth: 11

# The number of goals in the tree.
num_goals: 1000

# The maximum number of actions a node could have. Also known as the maximum branching factor.
max_actions: 4

# The average number of actions that a node has. Also known as the average branching factor.
# The branching factor of each node follows a binomial distribution.
avg_actions: 2.6
