# The maximum depth of the tree.
max_depth: 8

# The depth of the tree where the goals are located.
goals_depth: 8

# The number of goals in the tree.
num_goals: 50

# The maximum number of actions a node could have. Also known as the maximum branching factor.
max_actions: 8

# The minimum number of actions a node could have. Also known as the minimum branching factor.
min_actions: 4
