# The maximum depth of the tree.
max_depth: 4

# The number of goals in the tree.
num_goals: 10

# The maximum number of actions a node could have. Also known as the maximum branching factor.
max_actions: 3

# The average number of actions that a node has. Also known as the average branching factor.
# The branching factor of each node follows a binomial distribution.
avg_actions: 1.5
