# The maximum depth of the tree.
max_depth: 9

# The number of goals in the tree.
num_goals: 30

# The maximum number of actions a node could have. Also known as the maximum branching factor.
max_actions: 10

# The minimum number of actions a node could have. Also known as the minimum branching factor.
min_actions: 0
